# Generated by Django 3.0.8 on 2020-07-19 12:55

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20200718_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
