# Generated by Django 3.0.8 on 2020-07-19 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_county_mpoly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county',
            name='dis',
        ),
    ]
