# Generated by Django 3.0.8 on 2020-07-19 20:20

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0004_remove_county_dis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riot', models.TextField(max_length=100)),
                ('userId', models.IntegerField(default=0)),
                ('home', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('work', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('school', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
